{{- if gt .Values.hermes2Count 0.0 -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "rucio.fullname" . }}.config.hermes2.yaml
  labels:
    app: {{ template "rucio.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{- $common_config := .Values.config | default dict | mustToPrettyJson | b64enc }}
  {{- $component_config := .Values.hermes2.config | default dict | mustToPrettyJson | b64enc }}
  rucio.config.common.json: {{ $common_config | quote }}
  rucio.config.component.json: {{ $component_config | quote }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-hermes2
  labels:
    app: {{ template "rucio.name" . }}
    chart: {{ template "rucio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.hermes2Count }}
  selector:
    matchLabels:
      app: {{ template "rucio.name" . }}
      release: {{ .Release.Name }}
  strategy:
    type: {{ .Values.strategy.type }}
{{- if eq .Values.strategy.type "RollingUpdate" }}
    {{- with .Values.strategy.rollingUpdate }}
    rollingUpdate:
{{ toYaml . | trim | indent 6 }}
    {{- end }}
{{- end }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  template:
    metadata:
      labels:
        app: {{ template "rucio.name" . }}
        release: {{ .Release.Name }}
        rucio-daemon: hermes2
    {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
      annotations:
        checksum/config: {{ print "%s%s" $common_config $component_config | sha1sum }}
    {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.hermes2.podAnnotations }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
    spec:
    {{- if .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
    {{- end }}
      volumes:
        - name: config
          secret:
            secretName: {{ template "rucio.fullname" . }}.config.hermes2.yaml
{{ if .Values.hermes2.useSSL }}
        - name: usercert
          secret:
            secretName: {{ .Release.Name }}-hermes2-cert
        - name: userkey
          secret:
            secretName: {{ .Release.Name }}-hermes2-key
{{ end }}
        {{- range $key, $val := .Values.additionalSecrets }}
        - name: {{ $key }}
          secret:
            secretName: {{ $.Release.Name }}-{{ $val.secretName }}
        {{- end}}
        {{- range $key, $val := .Values.persistentVolumes }}
        - name: {{ $key }}
          persistentVolumeClaim:
            claimName: {{ $val.name }}
        {{- end}}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
{{ if .Values.hermes2.useSSL }}
            - name: usercert
              mountPath: /opt/rucio/certs/
            - name: userkey
              mountPath: /opt/rucio/keys/
{{ end }}
            - name: config
              mountPath: /opt/rucio/etc/rucio.config.common.json
              subPath: rucio.config.common.json
            - name: config
              mountPath: /opt/rucio/etc/rucio.config.component.json
              subPath: rucio.config.component.json
            {{- range $key, $val := .Values.additionalSecrets }}
            - name: {{ $key }}
              mountPath: {{ $val.mountPath }}
              subPath: {{ $val.subPath }}
            {{- end}}
            {{- range $key, $val := .Values.persistentVolumes }}
            - name: {{ $key }}
              mountPath: {{ $val.mountPath }}
            {{- end}}
          ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
          env:
            {{- range $key1, $val1 := .Values.optional_config }}
            - name: {{ $key1 | upper }}
              value: "{{ $val1  }}"
            {{- end}}
            - name: RUCIO_OVERRIDE_CONFIGS
              value: "/opt/rucio/etc/rucio.config.common.json /opt/rucio/etc/rucio.config.component.json"
            - name: RUCIO_DAEMON
              value: "hermes2"
            - name: RUCIO_DAEMON_ARGS
              value: "{{- if .Values.hermes2.threads }} --threads {{ .Values.hermes2.threads }}{{ end }} {{ if .Values.hermes2.bulk }} --bulk {{ .Values.hermes2.bulk }}{{ end }}"
{{- with .Values.hermes2.resources }}
          resources:
{{ toYaml . | trim | indent 12 }}
{{ end }}
{{- with .Values.hermes2.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.hermes2.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.hermes2.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
{{ end }}
