apiVersion: v1
kind: Service
metadata:
  name: {{ include "fts.fullname" . }}
  labels:
    {{- include "fts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port1 }}
      targetPort: fts1
      protocol: TCP
      name: fts1
    - port: {{ .Values.service.port2 }}
      targetPort: fts2
      protocol: TCP
      name: fts2
  selector:
    {{- include "fts.selectorLabels" . | nindent 4 }}

---

apiVersion: v1
kind: Service
metadata:
  name: ftsdb
  labels:
    {{- include "fts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3306
      targetPort: mysql
      protocol: TCP
      name: mysql
  selector:
    {{- include "fts.selectorLabels" . | nindent 4 }}
